### ISSUE TITLE
duplicate Sutro Bath entry in messages.ts

### ISSUE THREAD

**Issue by anderote** [NaimKabir/sfcommons-bot#4]
![image](https://user-images.githubusercontent.com/5619211/234731909-3ab1c72c-fbcf-48b0-b4ca-598efd9ffb5f.png)

options 1 and 3 were really hard to choose between

**Comment by NaimKabir** [comment]
hahaha

**Comment by NaimKabir** [comment]
fixed in commit [baa928c](https://github.com/NaimKabir/sfcommons-bot/commit/baa928cdf922c64a52f4b17e0b557071deaf4e18)
